(function () {
  const affiliateConfig = {
    merchantName: "Amazon",
    tag: "shopforher0b7-20",
    baseUrl: "https://www.amazon.com/s"
  };

  const tabs = [
    { id: "best-overall", label: "Best overall" },
    { id: "looks-expensive", label: "Looks expensive" },
    { id: "under-100", label: "Under $100" },
    { id: "cozy-home", label: "Cozy home" },
    { id: "daily-use", label: "Daily use" }
  ];

  const gifts = [
    {
      id: "silk-pillowcase",
      code: "GS-01",
      name: "Mulberry Silk Pillowcase Set",
      priceValue: 58,
      priceLabel: "$49 - $79",
      badge: "easy yes",
      hook: "Quiet luxury without trying too hard.",
      why: "Feels polished, feminine, and expensive without needing her exact size or taste.",
      bestFor: "girlfriend / wife / new relationship",
      vibe: "soft luxury",
      relationships: ["girlfriend", "wife", "anniversary", "new-relationship", "anyone"],
      intents: ["thoughtful", "looks-expensive", "cozy"],
      tabs: ["best-overall", "looks-expensive", "under-100", "cozy-home"],
      query: "mulberry silk pillowcase set gift for her",
      amazonAsin: "B09BFQG17F",
      baseScore: 95,
      accentFrom: "#c6dcff",
      accentTo: "#35689e"
    },
    {
      id: "temperature-mug",
      code: "GS-02",
      name: "Temperature-Control Mug",
      priceValue: 109,
      priceLabel: "$99 - $129",
      badge: "viral",
      hook: "Looks premium and gets used every day.",
      why: "A strong wife or girlfriend gift because it solves an annoying problem and feels upgraded immediately.",
      bestFor: "wife / girlfriend / coffee or tea",
      vibe: "quiet daily flex",
      relationships: ["girlfriend", "wife", "anniversary", "anyone"],
      intents: ["thoughtful", "daily-use", "looks-expensive", "everyday"],
      tabs: ["best-overall", "looks-expensive", "daily-use"],
      query: "temperature control mug gift for her",
      amazonAsin: "B08D3XPCZR",
      baseScore: 94,
      accentFrom: "#acd0ff",
      accentTo: "#2d649e"
    },
    {
      id: "digital-frame",
      code: "GS-03",
      name: "Digital Picture Frame",
      priceValue: 149,
      priceLabel: "$129 - $179",
      badge: "wife-safe",
      hook: "Personal without feeling cheesy.",
      why: "One of the cleanest meaningful gifts for wives because it feels emotional the second photos are loaded.",
      bestFor: "wife / anniversary / home",
      vibe: "emotional but clean",
      relationships: ["wife", "anniversary", "anyone"],
      intents: ["thoughtful", "looks-expensive", "cozy"],
      tabs: ["best-overall", "looks-expensive", "cozy-home"],
      query: "digital picture frame gift for wife",
      amazonAsin: "B0BG3F79LF",
      baseScore: 93,
      accentFrom: "#bdd8ff",
      accentTo: "#315f8f"
    },
    {
      id: "mini-photo-printer",
      code: "GS-04",
      name: "Mini Photo Printer",
      priceValue: 89,
      priceLabel: "$69 - $129",
      badge: "viral",
      hook: "Current, social, and very giftable.",
      why: "Easy girlfriend pick because it feels fun, personal, and shareable without being too serious.",
      bestFor: "girlfriend / anniversary / travel",
      vibe: "memory-driven",
      relationships: ["girlfriend", "anniversary", "new-relationship", "anyone"],
      intents: ["thoughtful", "viral", "looks-expensive"],
      tabs: ["best-overall", "under-100", "looks-expensive"],
      query: "mini photo printer gift for girlfriend",
      amazonAsin: "B0FM29Z95G",
      baseScore: 91,
      accentFrom: "#bad7ff",
      accentTo: "#2f6599"
    },
    {
      id: "sunrise-alarm",
      code: "GS-05",
      name: "Sunrise Alarm Clock",
      priceValue: 79,
      priceLabel: "$59 - $109",
      badge: "smart pick",
      hook: "Calm, modern, and hard to hate.",
      why: "Feels wellness-forward and designed, which makes it a good choice when you want thoughtful without overdoing it.",
      bestFor: "girlfriend / wife / home routine",
      vibe: "calm morning reset",
      relationships: ["girlfriend", "wife", "new-relationship", "anyone"],
      intents: ["thoughtful", "cozy", "everyday"],
      tabs: ["under-100", "cozy-home", "daily-use"],
      query: "sunrise alarm clock gift for her",
      amazonAsin: "B0C67ZDQLX",
      baseScore: 89,
      accentFrom: "#bfdcff",
      accentTo: "#4271a3"
    },
    {
      id: "luxury-throw",
      code: "GS-06",
      name: "Luxury Throw Blanket",
      priceValue: 59,
      priceLabel: "$39 - $89",
      badge: "comfort hit",
      hook: "Soft, elevated, no overthinking required.",
      why: "Very safe because it feels expensive, feminine, and cozy without forcing a specific personal taste.",
      bestFor: "girlfriend / wife / apartment",
      vibe: "cozy premium",
      relationships: ["girlfriend", "wife", "new-relationship", "anyone"],
      intents: ["cozy", "thoughtful", "looks-expensive"],
      tabs: ["under-100", "cozy-home", "looks-expensive"],
      query: "luxury throw blanket gift for her",
      amazonAsin: "B08KTS4KDT",
      baseScore: 90,
      accentFrom: "#d0e3ff",
      accentTo: "#4b78aa"
    },
    {
      id: "walking-pad",
      code: "GS-07",
      name: "Compact Walking Pad",
      priceValue: 219,
      priceLabel: "$179 - $329",
      badge: "big upgrade",
      hook: "A serious home-wellness move.",
      why: "The kind of wife gift that reads as useful, current, and more substantial than a small accessory.",
      bestFor: "wife / remote work / wellness",
      vibe: "high-value upgrade",
      relationships: ["wife", "anniversary", "anyone"],
      intents: ["everyday", "looks-expensive", "thoughtful"],
      tabs: ["best-overall", "looks-expensive", "daily-use"],
      query: "compact walking pad gift for wife",
      amazonAsin: "B0BVQMSVM1",
      baseScore: 88,
      accentFrom: "#c7ddff",
      accentTo: "#3c6b9b"
    },
    {
      id: "earbuds",
      code: "GS-08",
      name: "Noise-Canceling Earbuds",
      priceValue: 89,
      priceLabel: "$49 - $159",
      badge: "daily win",
      hook: "Useful enough to be a very safe bet.",
      why: "One of the easiest gifts for a girlfriend or wife because the use case is immediate and obvious.",
      bestFor: "girlfriend / wife / commute",
      vibe: "clean utility",
      relationships: ["girlfriend", "wife", "anyone"],
      intents: ["everyday", "viral", "thoughtful"],
      tabs: ["best-overall", "under-100", "daily-use"],
      query: "noise canceling earbuds gift for her",
      amazonAsin: "B0BZV4QFP8",
      baseScore: 92,
      accentFrom: "#b7d5ff",
      accentTo: "#305f92"
    },
    {
      id: "projector",
      code: "GS-09",
      name: "Portable Projector",
      priceValue: 129,
      priceLabel: "$89 - $189",
      badge: "date-night",
      hook: "A more memorable gift than another small object.",
      why: "Great when you want the gift to feel like an experience and a home upgrade at the same time.",
      bestFor: "wife / girlfriend / date nights",
      vibe: "weekend flex",
      relationships: ["girlfriend", "wife", "anniversary"],
      intents: ["looks-expensive", "cozy", "thoughtful"],
      tabs: ["looks-expensive", "cozy-home", "best-overall"],
      query: "portable projector gift for couples",
      amazonAsin: "B0FDGLZKKM",
      baseScore: 87,
      accentFrom: "#c2dbff",
      accentTo: "#2c5d8d"
    },
    {
      id: "magsafe-stand",
      code: "GS-10",
      name: "MagSafe Charging Stand",
      priceValue: 49,
      priceLabel: "$29 - $79",
      badge: "clean desk",
      hook: "Minimal, useful, and visually tidy.",
      why: "A professional-feeling option when she likes neat spaces, bedside setups, or a more polished desk.",
      bestFor: "girlfriend / wife / desk setup",
      vibe: "small clean upgrade",
      relationships: ["girlfriend", "wife", "new-relationship", "anyone"],
      intents: ["everyday", "looks-expensive"],
      tabs: ["under-100", "daily-use"],
      query: "magsafe charging stand gift for her",
      amazonAsin: "B0D8PYWHZR",
      baseScore: 86,
      accentFrom: "#bed9ff",
      accentTo: "#416c99"
    },
    {
      id: "jewelry-case",
      code: "GS-11",
      name: "Structured Jewelry Case",
      priceValue: 69,
      priceLabel: "$54 - $84",
      badge: "polished",
      hook: "Looks personal and expensive without being risky.",
      why: "A strong pick because it feels feminine, organized, and clearly chosen for her rather than bought at random.",
      bestFor: "girlfriend / wife / travel",
      vibe: "clean vanity piece",
      relationships: ["girlfriend", "wife", "anniversary", "anyone"],
      intents: ["thoughtful", "looks-expensive", "everyday"],
      tabs: ["best-overall", "looks-expensive", "under-100", "daily-use"],
      query: "structured jewelry case gift for her",
      amazonAsin: "B09TN9PWV2",
      baseScore: 90,
      accentFrom: "#cfe3ff",
      accentTo: "#4c79a6"
    },
    {
      id: "candle-warmer",
      code: "GS-12",
      name: "Candle Warmer Lamp",
      priceValue: 42,
      priceLabel: "$32 - $56",
      badge: "cozy",
      hook: "Very apartment-friendly and surprisingly elevated.",
      why: "Feels warm, aesthetic, and feminine, which makes it a low-risk cozy-home gift for a girlfriend or wife.",
      bestFor: "girlfriend / wife / apartment",
      vibe: "warm home detail",
      relationships: ["girlfriend", "wife", "new-relationship", "anyone"],
      intents: ["cozy", "thoughtful"],
      tabs: ["cozy-home", "under-100", "best-overall"],
      query: "candle warmer lamp gift for her",
      amazonAsin: "B0BWJRJYS7",
      baseScore: 88,
      accentFrom: "#d6e7ff",
      accentTo: "#5b82ad"
    },
    {
      id: "vanity-mirror",
      code: "GS-13",
      name: "LED Vanity Mirror",
      priceValue: 119,
      priceLabel: "$89 - $139",
      badge: "setup upgrade",
      hook: "A higher-end beauty-space upgrade that still feels practical.",
      why: "Useful, visual, and clearly premium, which makes it a stronger wife or long-term girlfriend option.",
      bestFor: "wife / girlfriend / beauty setup",
      vibe: "polished daily station",
      relationships: ["girlfriend", "wife", "anniversary"],
      intents: ["looks-expensive", "everyday"],
      tabs: ["looks-expensive", "daily-use", "best-overall"],
      query: "led vanity mirror gift for her",
      amazonAsin: "B0DBKXV48B",
      baseScore: 87,
      accentFrom: "#c6ddff",
      accentTo: "#3d6c99"
    },
    {
      id: "cashmere-robe",
      code: "GS-14",
      name: "Cashmere-Feel Robe",
      priceValue: 139,
      priceLabel: "$109 - $159",
      badge: "wife-level",
      hook: "Soft luxury that reads intentional fast.",
      why: "One of the better elevated home gifts because it feels personal, premium, and clearly for her comfort.",
      bestFor: "wife / anniversary / home",
      vibe: "soft luxury",
      relationships: ["wife", "anniversary", "anyone"],
      intents: ["cozy", "looks-expensive", "thoughtful"],
      tabs: ["looks-expensive", "cozy-home", "best-overall"],
      query: "luxury robe gift for wife",
      amazonAsin: "B079B9CWRN",
      baseScore: 89,
      accentFrom: "#d0e3ff",
      accentTo: "#527ba7"
    },
    {
      id: "kindle-paperwhite",
      code: "GS-15",
      name: "Kindle Paperwhite Signature Edition",
      priceValue: 189,
      priceLabel: "$159 - $209",
      badge: "reader upgrade",
      hook: "Quiet premium gift with real daily payoff.",
      why: "Feels thoughtful and polished, especially when she reads at night, travels, or wants a cleaner way to unwind.",
      bestFor: "girlfriend / wife / reader",
      vibe: "smart downtime",
      relationships: ["girlfriend", "wife", "anniversary", "anyone"],
      intents: ["thoughtful", "everyday", "looks-expensive"],
      tabs: ["best-overall", "looks-expensive", "daily-use"],
      query: "Kindle Paperwhite Signature Edition gift for her",
      amazonAsin: "B0DC85J75V",
      imageUrl: "https://m.media-amazon.com/images/I/81I4120duxL._AC_SY300_SX300_QL70_ML2_.jpg",
      baseScore: 92,
      accentFrom: "#c4dcff",
      accentTo: "#386897"
    },
    {
      id: "ninja-creami",
      code: "GS-16",
      name: "Ninja CREAMi Deluxe",
      priceValue: 199,
      priceLabel: "$179 - $229",
      badge: "viral",
      hook: "The fun kitchen gift that actually keeps getting used.",
      why: "Strong when she likes hosting, dessert, or wellness routines and you want a more current-feeling home gift.",
      bestFor: "girlfriend / wife / kitchen",
      vibe: "playful upgrade",
      relationships: ["girlfriend", "wife", "anniversary", "anyone"],
      intents: ["viral", "everyday", "thoughtful"],
      tabs: ["best-overall", "daily-use", "looks-expensive"],
      query: "Ninja CREAMi Deluxe gift for her",
      amazonAsin: "B0B9CZ6XBQ",
      imageUrl: "https://m.media-amazon.com/images/I/71JYt9fprVL._AC_SY300_SX300_QL70_ML2_.jpg",
      baseScore: 90,
      accentFrom: "#cce1ff",
      accentTo: "#4673a5"
    },
    {
      id: "nespresso-machine",
      code: "GS-17",
      name: "Nespresso Vertuo Next",
      priceValue: 149,
      priceLabel: "$119 - $179",
      badge: "morning flex",
      hook: "A cleaner coffee upgrade than another random gadget.",
      why: "Feels elevated right away and makes the everyday routine look more put together.",
      bestFor: "wife / girlfriend / coffee",
      vibe: "countertop luxury",
      relationships: ["girlfriend", "wife", "anniversary", "anyone"],
      intents: ["everyday", "looks-expensive", "thoughtful"],
      tabs: ["best-overall", "looks-expensive", "daily-use"],
      query: "Nespresso Vertuo Next gift for her",
      amazonAsin: "B084GY7284",
      imageUrl: "https://m.media-amazon.com/images/I/51gQiltmkIL.__AC_SX300_SY300_QL70_ML2_.jpg",
      baseScore: 90,
      accentFrom: "#d1e4ff",
      accentTo: "#567ea8"
    },
    {
      id: "owala-bottle",
      code: "GS-18",
      name: "Owala FreeSip Sway Bottle",
      priceValue: 40,
      priceLabel: "$35 - $45",
      badge: "viral",
      hook: "Current, practical, and easy to justify.",
      why: "Low-risk when she likes stylish everyday gear and you want something current without overspending.",
      bestFor: "girlfriend / wife / gym bag",
      vibe: "cute utility",
      relationships: ["girlfriend", "wife", "new-relationship", "anyone"],
      intents: ["everyday", "viral", "thoughtful"],
      tabs: ["under-100", "daily-use", "best-overall"],
      query: "Owala FreeSip Sway bottle gift for her",
      amazonAsin: "B0FJZDV6BH",
      imageUrl: "https://cdn.shopify.com/s/files/1/0439/2537/3087/files/OW_90s_kid_30oz_FreeSip_Sway_Side.png?crop=center&height=500&v=1772218716&width=500",
      baseScore: 87,
      accentFrom: "#c7ddff",
      accentTo: "#4a739f"
    },
    {
      id: "theragun-relief",
      code: "GS-19",
      name: "Therabody Theragun Relief",
      priceValue: 149,
      priceLabel: "$129 - $159",
      badge: "wellness",
      hook: "Feels substantial and useful right away.",
      why: "A better premium wellness gift when you want something more serious than a small accessory.",
      bestFor: "wife / girlfriend / workouts",
      vibe: "recovery upgrade",
      relationships: ["girlfriend", "wife", "anniversary", "anyone"],
      intents: ["everyday", "thoughtful", "looks-expensive"],
      tabs: ["best-overall", "daily-use", "looks-expensive"],
      query: "Theragun Relief gift for her",
      amazonAsin: "B0CNS894RH",
      imageUrl: "https://m.media-amazon.com/images/I/61f9mqZJ4rL._AC_SY300_SX300_QL70_ML2_.jpg",
      baseScore: 89,
      accentFrom: "#bdd8ff",
      accentTo: "#426d9a"
    },
    {
      id: "ugg-slippers",
      code: "GS-20",
      name: "Koolaburra by UGG Burree Slipper",
      priceValue: 65,
      priceLabel: "$55 - $80",
      badge: "cozy",
      hook: "Soft, branded, and easier than sizing a full shoe.",
      why: "Reads more intentional than a generic home gift and lands fast if she likes comfort and warm routines.",
      bestFor: "girlfriend / wife / home",
      vibe: "cozy branded comfort",
      relationships: ["girlfriend", "wife", "anniversary", "anyone"],
      intents: ["cozy", "looks-expensive", "thoughtful"],
      tabs: ["best-overall", "under-100", "cozy-home", "looks-expensive"],
      query: "UGG slippers gift for her",
      amazonAsin: "B0CB978WSZ",
      imageUrl: "https://cdn.file-sync.shop/cdn/429/2024/10/26/thumb300-main-Koolaburra-by-UGG-Womens-Burree-SlipperBlack-5492712-1007725.webp",
      baseScore: 90,
      accentFrom: "#d7e7ff",
      accentTo: "#6489af"
    },
    {
      id: "stanley-quencher",
      code: "GS-21",
      name: "Stanley Quencher H2.0 FlowState",
      priceValue: 45,
      priceLabel: "$35 - $50",
      badge: "viral",
      hook: "Still a mainstream yes when she actually uses it.",
      why: "Works because it is instantly recognizable, easy to carry every day, and giftable without much explanation.",
      bestFor: "girlfriend / wife / daily carry",
      vibe: "trend with utility",
      relationships: ["girlfriend", "wife", "new-relationship", "anyone"],
      intents: ["viral", "everyday"],
      tabs: ["best-overall", "under-100", "daily-use"],
      query: "Stanley Quencher H2.0 gift for her",
      amazonAsin: "B0FB7LKQXV",
      imageUrl: "https://m.media-amazon.com/images/I/41xhWXRupeL._AC_SY300_SX300_QL70_ML2_.jpg",
      baseScore: 86,
      accentFrom: "#bdd6ff",
      accentTo: "#3f6b97"
    },
    {
      id: "laneige-set",
      code: "GS-22",
      name: "LANEIGE Midnight Minis Lip Set",
      priceValue: 24,
      priceLabel: "$20 - $28",
      badge: "small luxury",
      hook: "Tiny spend, high gift energy.",
      why: "Good add-on or lower-budget pick when you want something beauty-adjacent that still feels current and polished.",
      bestFor: "girlfriend / stocking / add-on",
      vibe: "beauty desk candy",
      relationships: ["girlfriend", "wife", "new-relationship", "anyone"],
      intents: ["thoughtful", "looks-expensive", "viral"],
      tabs: ["best-overall", "under-100", "looks-expensive"],
      query: "LANEIGE Midnight Minis Lip Set gift for her",
      amazonAsin: "B0F24ZZN95",
      imageUrl: "https://whitehorseboutique.com/cdn/shop/files/2AEBDE3C-93A3-49B7-BB15-A411975436CC.jpg?v=1732737545&width=1445",
      baseScore: 85,
      accentFrom: "#d9e8ff",
      accentTo: "#6a8eb3"
    },
    {
      id: "bose-speaker",
      code: "GS-23",
      name: "Bose SoundLink Flex (2nd Gen)",
      priceValue: 149,
      priceLabel: "$129 - $159",
      badge: "daily win",
      hook: "Portable, premium, and easier to use than explain.",
      why: "A clean option when she likes music, travel, or outdoor hangs and you want something with stronger brand recognition.",
      bestFor: "girlfriend / wife / travel",
      vibe: "premium portability",
      relationships: ["girlfriend", "wife", "anniversary", "anyone"],
      intents: ["everyday", "looks-expensive", "thoughtful"],
      tabs: ["best-overall", "daily-use", "looks-expensive"],
      query: "Bose SoundLink Flex 2nd Gen gift for her",
      amazonAsin: "B0D6W8X6L2",
      imageUrl: "https://assets.bosecreative.com/transform/7a38af47-ac9d-4a4e-8b49-e6d6b2a9e2bb/SLFLXII_AlpineSage_SF_PDP_Gallery_01?io=width%3A816%2Cheight%3A667%2Ctransform%3Afit&io=width%3A816%2Cheight%3A667%2Ctransform%3Afit&quality=90",
      baseScore: 88,
      accentFrom: "#c7ddff",
      accentTo: "#446f9c"
    },
    {
      id: "sol-de-janeiro",
      code: "GS-24",
      name: "Sol de Janeiro Bum Bum Jet Set",
      priceValue: 32,
      priceLabel: "$28 - $36",
      badge: "viral",
      hook: "Beauty-category gift that already feels popular.",
      why: "Useful when you want a smaller beauty pick that still feels current, feminine, and clearly chosen for her.",
      bestFor: "girlfriend / wife / beauty",
      vibe: "vacation-energy mini set",
      relationships: ["girlfriend", "wife", "new-relationship", "anyone"],
      intents: ["viral", "thoughtful", "looks-expensive"],
      tabs: ["best-overall", "under-100", "looks-expensive"],
      query: "Sol de Janeiro Bum Bum Jet Set gift for her",
      imageUrl: "https://www.cultbeauty.com/images?auto=avif&fit=cover&format=webp&height=985&url=https%3A%2F%2Fstatic.thcdn.com%2Fproductimg%2Foriginal%2F12545102-1214895116732476.jpg&width=985",
      baseScore: 84,
      accentFrom: "#d4e5ff",
      accentTo: "#5b83ad"
    }
  ];

  window.GiftsherCatalog = {
    affiliateConfig,
    tabs,
    gifts
  };
}());
