(function () {
  const affiliateConfig = {
    merchantName: "Amazon",
    tag: "giftsher-20",
    baseUrl: "https://www.amazon.com/s"
  };

  const tabs = [
    { id: "best-overall", label: "Best overall" },
    { id: "looks-expensive", label: "Looks expensive" },
    { id: "under-100", label: "Under $100" },
    { id: "cozy-home", label: "Cozy home" },
    { id: "daily-use", label: "Daily use" }
  ];

  const gifts = [
    {
      id: "silk-pillowcase",
      code: "GS-01",
      name: "Mulberry Silk Pillowcase Set",
      priceValue: 58,
      priceLabel: "$49 - $79",
      badge: "easy yes",
      hook: "Quiet luxury without trying too hard.",
      why: "Feels polished, feminine, and expensive without needing her exact size or taste.",
      bestFor: "girlfriend / wife / new relationship",
      vibe: "soft luxury",
      relationships: ["girlfriend", "wife", "anniversary", "new-relationship", "anyone"],
      intents: ["thoughtful", "looks-expensive", "cozy"],
      tabs: ["best-overall", "looks-expensive", "under-100", "cozy-home"],
      query: "mulberry silk pillowcase set gift for her",
      baseScore: 95,
      accentFrom: "#c6dcff",
      accentTo: "#35689e"
    },
    {
      id: "temperature-mug",
      code: "GS-02",
      name: "Temperature-Control Mug",
      priceValue: 109,
      priceLabel: "$99 - $129",
      badge: "viral",
      hook: "Looks premium and gets used every day.",
      why: "A strong wife or girlfriend gift because it solves an annoying problem and feels upgraded immediately.",
      bestFor: "wife / girlfriend / coffee or tea",
      vibe: "quiet daily flex",
      relationships: ["girlfriend", "wife", "anniversary", "anyone"],
      intents: ["thoughtful", "daily-use", "looks-expensive", "everyday"],
      tabs: ["best-overall", "looks-expensive", "daily-use"],
      query: "temperature control mug gift for her",
      baseScore: 94,
      accentFrom: "#acd0ff",
      accentTo: "#2d649e"
    },
    {
      id: "digital-frame",
      code: "GS-03",
      name: "Digital Picture Frame",
      priceValue: 149,
      priceLabel: "$129 - $179",
      badge: "wife-safe",
      hook: "Personal without feeling cheesy.",
      why: "One of the cleanest meaningful gifts for wives because it feels emotional the second photos are loaded.",
      bestFor: "wife / anniversary / home",
      vibe: "emotional but clean",
      relationships: ["wife", "anniversary", "anyone"],
      intents: ["thoughtful", "looks-expensive", "cozy"],
      tabs: ["best-overall", "looks-expensive", "cozy-home"],
      query: "digital picture frame gift for wife",
      baseScore: 93,
      accentFrom: "#bdd8ff",
      accentTo: "#315f8f"
    },
    {
      id: "mini-photo-printer",
      code: "GS-04",
      name: "Mini Photo Printer",
      priceValue: 89,
      priceLabel: "$69 - $129",
      badge: "viral",
      hook: "Current, social, and very giftable.",
      why: "Easy girlfriend pick because it feels fun, personal, and shareable without being too serious.",
      bestFor: "girlfriend / anniversary / travel",
      vibe: "memory-driven",
      relationships: ["girlfriend", "anniversary", "new-relationship", "anyone"],
      intents: ["thoughtful", "viral", "looks-expensive"],
      tabs: ["best-overall", "under-100", "looks-expensive"],
      query: "mini photo printer gift for girlfriend",
      baseScore: 91,
      accentFrom: "#bad7ff",
      accentTo: "#2f6599"
    },
    {
      id: "sunrise-alarm",
      code: "GS-05",
      name: "Sunrise Alarm Clock",
      priceValue: 79,
      priceLabel: "$59 - $109",
      badge: "smart pick",
      hook: "Calm, modern, and hard to hate.",
      why: "Feels wellness-forward and designed, which makes it a good choice when you want thoughtful without overdoing it.",
      bestFor: "girlfriend / wife / home routine",
      vibe: "calm morning reset",
      relationships: ["girlfriend", "wife", "new-relationship", "anyone"],
      intents: ["thoughtful", "cozy", "everyday"],
      tabs: ["under-100", "cozy-home", "daily-use"],
      query: "sunrise alarm clock gift for her",
      baseScore: 89,
      accentFrom: "#bfdcff",
      accentTo: "#4271a3"
    },
    {
      id: "luxury-throw",
      code: "GS-06",
      name: "Luxury Throw Blanket",
      priceValue: 59,
      priceLabel: "$39 - $89",
      badge: "comfort hit",
      hook: "Soft, elevated, no overthinking required.",
      why: "Very safe because it feels expensive, feminine, and cozy without forcing a specific personal taste.",
      bestFor: "girlfriend / wife / apartment",
      vibe: "cozy premium",
      relationships: ["girlfriend", "wife", "new-relationship", "anyone"],
      intents: ["cozy", "thoughtful", "looks-expensive"],
      tabs: ["under-100", "cozy-home", "looks-expensive"],
      query: "luxury throw blanket gift for her",
      baseScore: 90,
      accentFrom: "#d0e3ff",
      accentTo: "#4b78aa"
    },
    {
      id: "walking-pad",
      code: "GS-07",
      name: "Compact Walking Pad",
      priceValue: 219,
      priceLabel: "$179 - $329",
      badge: "big upgrade",
      hook: "A serious home-wellness move.",
      why: "The kind of wife gift that reads as useful, current, and more substantial than a small accessory.",
      bestFor: "wife / remote work / wellness",
      vibe: "high-value upgrade",
      relationships: ["wife", "anniversary", "anyone"],
      intents: ["everyday", "looks-expensive", "thoughtful"],
      tabs: ["best-overall", "looks-expensive", "daily-use"],
      query: "compact walking pad gift for wife",
      baseScore: 88,
      accentFrom: "#c7ddff",
      accentTo: "#3c6b9b"
    },
    {
      id: "earbuds",
      code: "GS-08",
      name: "Noise-Canceling Earbuds",
      priceValue: 89,
      priceLabel: "$49 - $159",
      badge: "daily win",
      hook: "Useful enough to be a very safe bet.",
      why: "One of the easiest gifts for a girlfriend or wife because the use case is immediate and obvious.",
      bestFor: "girlfriend / wife / commute",
      vibe: "clean utility",
      relationships: ["girlfriend", "wife", "anyone"],
      intents: ["everyday", "viral", "thoughtful"],
      tabs: ["best-overall", "under-100", "daily-use"],
      query: "noise canceling earbuds gift for her",
      baseScore: 92,
      accentFrom: "#b7d5ff",
      accentTo: "#305f92"
    },
    {
      id: "projector",
      code: "GS-09",
      name: "Portable Projector",
      priceValue: 129,
      priceLabel: "$89 - $189",
      badge: "date-night",
      hook: "A more memorable gift than another small object.",
      why: "Great when you want the gift to feel like an experience and a home upgrade at the same time.",
      bestFor: "wife / girlfriend / date nights",
      vibe: "weekend flex",
      relationships: ["girlfriend", "wife", "anniversary"],
      intents: ["looks-expensive", "cozy", "thoughtful"],
      tabs: ["looks-expensive", "cozy-home", "best-overall"],
      query: "portable projector gift for couples",
      baseScore: 87,
      accentFrom: "#c2dbff",
      accentTo: "#2c5d8d"
    },
    {
      id: "magsafe-stand",
      code: "GS-10",
      name: "MagSafe Charging Stand",
      priceValue: 49,
      priceLabel: "$29 - $79",
      badge: "clean desk",
      hook: "Minimal, useful, and visually tidy.",
      why: "A professional-feeling option when she likes neat spaces, bedside setups, or a more polished desk.",
      bestFor: "girlfriend / wife / desk setup",
      vibe: "small clean upgrade",
      relationships: ["girlfriend", "wife", "new-relationship", "anyone"],
      intents: ["everyday", "looks-expensive"],
      tabs: ["under-100", "daily-use"],
      query: "magsafe charging stand gift for her",
      baseScore: 86,
      accentFrom: "#bed9ff",
      accentTo: "#416c99"
    },
    {
      id: "jewelry-case",
      code: "GS-11",
      name: "Structured Jewelry Case",
      priceValue: 69,
      priceLabel: "$54 - $84",
      badge: "polished",
      hook: "Looks personal and expensive without being risky.",
      why: "A strong pick because it feels feminine, organized, and clearly chosen for her rather than bought at random.",
      bestFor: "girlfriend / wife / travel",
      vibe: "clean vanity piece",
      relationships: ["girlfriend", "wife", "anniversary", "anyone"],
      intents: ["thoughtful", "looks-expensive", "everyday"],
      tabs: ["best-overall", "looks-expensive", "under-100", "daily-use"],
      query: "structured jewelry case gift for her",
      baseScore: 90,
      accentFrom: "#cfe3ff",
      accentTo: "#4c79a6"
    },
    {
      id: "candle-warmer",
      code: "GS-12",
      name: "Candle Warmer Lamp",
      priceValue: 42,
      priceLabel: "$32 - $56",
      badge: "cozy",
      hook: "Very apartment-friendly and surprisingly elevated.",
      why: "Feels warm, aesthetic, and feminine, which makes it a low-risk cozy-home gift for a girlfriend or wife.",
      bestFor: "girlfriend / wife / apartment",
      vibe: "warm home detail",
      relationships: ["girlfriend", "wife", "new-relationship", "anyone"],
      intents: ["cozy", "thoughtful"],
      tabs: ["cozy-home", "under-100", "best-overall"],
      query: "candle warmer lamp gift for her",
      baseScore: 88,
      accentFrom: "#d6e7ff",
      accentTo: "#5b82ad"
    },
    {
      id: "vanity-mirror",
      code: "GS-13",
      name: "LED Vanity Mirror",
      priceValue: 119,
      priceLabel: "$89 - $139",
      badge: "setup upgrade",
      hook: "A higher-end beauty-space upgrade that still feels practical.",
      why: "Useful, visual, and clearly premium, which makes it a stronger wife or long-term girlfriend option.",
      bestFor: "wife / girlfriend / beauty setup",
      vibe: "polished daily station",
      relationships: ["girlfriend", "wife", "anniversary"],
      intents: ["looks-expensive", "everyday"],
      tabs: ["looks-expensive", "daily-use", "best-overall"],
      query: "led vanity mirror gift for her",
      baseScore: 87,
      accentFrom: "#c6ddff",
      accentTo: "#3d6c99"
    },
    {
      id: "cashmere-robe",
      code: "GS-14",
      name: "Cashmere-Feel Robe",
      priceValue: 139,
      priceLabel: "$109 - $159",
      badge: "wife-level",
      hook: "Soft luxury that reads intentional fast.",
      why: "One of the better elevated home gifts because it feels personal, premium, and clearly for her comfort.",
      bestFor: "wife / anniversary / home",
      vibe: "soft luxury",
      relationships: ["wife", "anniversary", "anyone"],
      intents: ["cozy", "looks-expensive", "thoughtful"],
      tabs: ["looks-expensive", "cozy-home", "best-overall"],
      query: "luxury robe gift for wife",
      baseScore: 89,
      accentFrom: "#d0e3ff",
      accentTo: "#527ba7"
    }
  ];

  window.GiftsherCatalog = {
    affiliateConfig,
    tabs,
    gifts
  };
}());
