const allRelationships = ["girlfriend", "wife", "anniversary", "new-relationship", "anyone"];

function createImportedItem(item) {
  return {
    relationships: allRelationships,
    intents: ["thoughtful"],
    tabs: ["best-overall"],
    badge: "gift pick",
    bestFor: "girlfriend / wife",
    vibe: "clean find",
    baseScore: 74,
    ...item,
  };
}

// Imported from a user-provided Amazon list on 2026-03-09.
// Entries without a direct ASIN still use exact-title Amazon search queries.
export const importedCatalogItems = [
  createImportedItem({
    id: "saodimallsu-crochet-coverup-set",
    slug: "saodimallsu-crochet-cover-up-set",
    code: "GS-25",
    brand: "Saodimallsu",
    name: "Saodimallsu Crochet Swim Cover Up Set",
    priceValue: 39.99,
    priceLabel: "$39.99",
    badge: "beach set",
    hook: "A two-piece beach layer that looks more styled than a basic cover-up.",
    why: "Useful when you want a warm-weather gift that feels trend-aware without overcomplicating the pick.",
    bestFor: "girlfriend / wife / beach trip",
    vibe: "boho vacation layer",
    intents: ["looks-expensive", "viral", "thoughtful"],
    tabs: ["looks-expensive", "under-100"],
    sourceProductUrl: "https://giftpals.com/item/saodimallsu-womens-crochet-swim-cover-up-2-piece-v-neck-3",
    query:
      "Saodimallsu Womens Crochet Swim Cover Up 2 Piece V Neck Long Sleeve Wrap Tie Crop Tops Beach Boho Maxi Coverup Set",
    baseScore: 76,
  }),
  createImportedItem({
    id: "roseseek-crochet-lace-pants",
    slug: "roseseek-crochet-lace-cover-up-pants",
    code: "GS-26",
    brand: "RoseSeek",
    name: "RoseSeek Crochet Lace Cover Up Pants",
    priceValue: 40.99,
    priceLabel: "$40.99 - $42.99",
    badge: "beach layer",
    hook: "A lighter summer add-on that feels dressier than standard swim cover-ups.",
    why: "Works when she likes resortwear styling and you want a lower-risk fashion gift with an easy vacation angle.",
    bestFor: "girlfriend / wife / beach vacation",
    vibe: "sheer coastal layer",
    intents: ["looks-expensive", "viral"],
    tabs: ["looks-expensive", "under-100"],
    query:
      "RoseSeek Women's Crochet Lace Pants Ruffle Layered Elastic Waist Mesh Bathing Suit Cover Up Beach Pants",
    baseScore: 75,
  }),
  createImportedItem({
    id: "saodimallsu-crochet-cardigan-dress",
    slug: "saodimallsu-crochet-cardigan-cover-up-dress",
    code: "GS-27",
    brand: "Saodimallsu",
    name: "Saodimallsu Crochet Cardigan Cover Up Dress",
    priceValue: 39.98,
    priceLabel: "$39.98 - $42.99",
    badge: "vacation layer",
    hook: "A button-down crochet cover-up that reads easy, current, and vacation-ready.",
    why: "A safer apparel-adjacent gift when you want something visual and seasonal without jumping to a full dress buy.",
    bestFor: "girlfriend / wife / resort trip",
    vibe: "coastal cardigan mini",
    intents: ["looks-expensive", "viral"],
    tabs: ["looks-expensive", "under-100"],
    sourceProductUrl: "https://giftpals.com/item/saodimallsu-womens-crochet-swimsuit-cover-up-long-bell",
    query:
      "Saodimallsu Womens Crochet Swimsuit Coverup Button Down Long Sleeve Cardigan Mini Dress Beach Cover Ups Vacation Outfits",
    baseScore: 76,
  }),
  createImportedItem({
    id: "sheer-crochet-poncho-top",
    slug: "sheer-crochet-poncho-top",
    code: "GS-28",
    name: "Sheer Crochet Poncho Top",
    priceValue: 10.99,
    priceLabel: "$10.99 - $34.99",
    badge: "light layer",
    hook: "A very lightweight throw-on piece for beachwear, tanks, or warmer weather outfits.",
    why: "Easy to justify as a lower-cost style add-on when you want something breezy and visibly giftable.",
    bestFor: "girlfriend / wife / warm weather",
    vibe: "airy mesh shrug",
    intents: ["looks-expensive", "thoughtful"],
    tabs: ["under-100", "looks-expensive"],
    amazonAsin: "B0FGPM7DPD",
    sourceProductUrl: "https://www.amazon.com/dp/B0FGPM7DPD",
    query:
      "Women Sheer Poncho Top Lightweight Knit Crochet Shrug Bolero Mesh Batwing Sleeve Sweater Cover Up Beachwear",
    baseScore: 72,
  }),
  createImportedItem({
    id: "panluca-statement-necklace",
    slug: "panluca-statement-necklace",
    code: "GS-29",
    brand: "PanLuca",
    name: "PanLuca Statement Necklace",
    priceValue: 33.99,
    priceLabel: "$33.99",
    badge: "statement",
    hook: "A colorful oversized necklace that feels bold immediately out of the box.",
    why: "Strong when she likes noticeable accessories and you want a jewelry gift with more visual payoff than tiny basics.",
    bestFor: "girlfriend / wife / statement jewelry",
    vibe: "color-pop accessory",
    intents: ["looks-expensive", "thoughtful", "viral"],
    tabs: ["best-overall", "looks-expensive", "under-100"],
    amazonAsin: "B0FLXQJV9Z",
    sourceProductUrl: "https://www.amazon.com/dp/B0FLXQJV9Z",
    query:
      "PanLuca Miniature Semi-Precious Stone & Oversized Multi-Color Resin Bead Statement Necklace 17+3 Extender Chain Chunky Eye-Catching Beads Bold Fashion Jewelry Gift for Women",
    baseScore: 77,
  }),
  createImportedItem({
    id: "posadina-phone-charm",
    slug: "posadina-natural-stone-phone-charm",
    code: "GS-30",
    brand: "Posadina",
    name: "Posadina Natural Stone Phone Charm",
    priceValue: 14.99,
    priceLabel: "$14.99 - $17.99",
    badge: "daily charm",
    hook: "A beaded phone wrist strap that lands somewhere between accessory and everyday utility.",
    why: "A cleaner small gift when she likes personalized-looking extras that attach to something she already uses daily.",
    bestFor: "girlfriend / wife / small add-on",
    vibe: "beaded everyday detail",
    intents: ["everyday", "thoughtful", "viral"],
    tabs: ["under-100", "daily-use", "best-overall"],
    amazonAsin: "B0F7XNGFSJ",
    sourceProductUrl: "https://www.amazon.com/dp/B0F7XNGFSJ",
    query:
      "Posadina Natural Stone Phone Charm, Beaded Healing Phone Wrist Strap, Handmade Cellphone Chain Lanyard with Tether Tab",
    baseScore: 78,
  }),
  createImportedItem({
    id: "mchic-beaded-choker",
    slug: "mchic-colorful-beaded-choker",
    code: "GS-31",
    brand: "Mchic",
    name: "Mchic Colorful Beaded Choker Necklace",
    priceValue: 14.99,
    priceLabel: "$14.99",
    badge: "summer color",
    hook: "A low-cost jewelry pick with obvious beach and summer energy.",
    why: "Useful when you want a playful accessory gift that feels trend-aware without a big spend.",
    bestFor: "girlfriend / wife / summer styling",
    vibe: "surfer-inspired color",
    intents: ["viral", "looks-expensive", "thoughtful"],
    tabs: ["under-100", "looks-expensive", "best-overall"],
    query:
      "Mchic Colorful Beaded Choker Necklace for Women Boho Large Square Acrylic Beaded Necklace Stainless Steel Adjustable Surfer Beach Strand Necklces Summer Handmade Jewelry Gift for Women",
    baseScore: 74,
  }),
  createImportedItem({
    id: "boxwood-bunny-topiary",
    slug: "boxwood-bunny-topiary",
    code: "GS-32",
    name: "Boxwood Bunny Topiary",
    priceValue: 88.99,
    priceLabel: "$88.99",
    badge: "seasonal",
    hook: "A larger Easter porch piece that feels more finished than small tabletop decor.",
    why: "Better when you want spring decor to read intentional and gift-ready rather than like filler basket extras.",
    bestFor: "wife / spring decorating / porch",
    vibe: "front-door spring accent",
    relationships: ["wife", "anniversary", "anyone"],
    intents: ["cozy", "thoughtful", "looks-expensive"],
    tabs: ["cozy-home", "looks-expensive", "under-100"],
    amazonAsin: "B0G4BZL9L7",
    sourceProductUrl: "https://www.amazon.com/dp/B0G4BZL9L7",
    query:
      "Easter Decorations 3 Ft Boxwood Bunny Topiary with Bow Artificial Bunny Shaped Tree with Planter Pot for Indoor Outdoor Decor Spring Decoration for Home Yard Front Door Porch Mantle Party",
    baseScore: 73,
  }),
  createImportedItem({
    id: "lenox-bunny-candy-dish",
    slug: "lenox-wicker-creek-bunny-candy-dish",
    code: "GS-33",
    brand: "Lenox",
    name: "Lenox Wicker Creek Bunny Candy Dish",
    priceValue: 29.95,
    priceLabel: "$29.95",
    badge: "tabletop",
    hook: "A branded seasonal dish that feels more giftable than generic Easter decor.",
    why: "A cleaner pick for someone who likes tableware, hosting pieces, or a recognizable home brand.",
    bestFor: "wife / host gift / spring table",
    vibe: "spring serveware accent",
    relationships: ["wife", "anniversary", "anyone"],
    intents: ["cozy", "thoughtful", "looks-expensive"],
    tabs: ["cozy-home", "under-100", "best-overall"],
    amazonAsin: "B0DTVR2YWZ",
    sourceProductUrl: "https://www.amazon.com/dp/B0DTVR2YWZ",
    query: "Lenox 897157 Wicker Creek Bunny Candy Dish, Easter Serveware",
    baseScore: 75,
  }),
  createImportedItem({
    id: "easter-bunny-porch-decor",
    slug: "large-easter-bunny-porch-decor",
    code: "GS-34",
    name: "Large Easter Bunny Porch Decor",
    priceValue: 43.99,
    priceLabel: "$43.99 - $45.99",
    badge: "porch decor",
    hook: "A larger seasonal bunny statue that reads clearly from the porch or entryway.",
    why: "Fits when she likes exterior seasonal decor and you want something more visible than tabletop pieces.",
    bestFor: "wife / porch decorating / seasonal home",
    vibe: "outdoor spring statement",
    relationships: ["wife", "anniversary", "anyone"],
    intents: ["cozy", "thoughtful"],
    tabs: ["cozy-home", "under-100"],
    sourceProductUrl: "https://www.walmart.com/ip/19338462416",
    query: "Easter Bunny Decor, Large Bunnies Statue Outdoor Porch Decor",
    baseScore: 71,
  }),
  createImportedItem({
    id: "oliker-speckled-eggs",
    slug: "oliker-speckled-eggs",
    code: "GS-35",
    brand: "OLIKER",
    name: "OLIKER Speckled Easter Eggs",
    priceValue: 12.99,
    priceLabel: "$12.99 - $18.99",
    badge: "basket filler",
    hook: "A simple seasonal filler pack for spring centerpieces, baskets, or bowls.",
    why: "Useful as an add-on when you need low-cost Easter decor rather than a standalone main gift.",
    bestFor: "host gift / Easter setup / add-on",
    vibe: "spring filler set",
    relationships: ["anyone"],
    intents: ["cozy", "thoughtful"],
    tabs: ["cozy-home", "under-100"],
    amazonAsin: "B0DSBGK88Q",
    sourceProductUrl: "https://www.amazon.com/dp/B0DSBGK88Q",
    query:
      "OLIKER 24 Pcs Easter Speckled Eggs, 2.4in 4 Colors Plastic Speckled Eggs and Vase Filler Faux Chicken Eggs for Easter Decorations Basket Filler Vase Decorating",
    baseScore: 68,
  }),
  createImportedItem({
    id: "easter-gift-basket",
    slug: "easter-gift-basket-with-ribbons",
    code: "GS-36",
    name: "Easter Gift Basket with Ribbons",
    priceValue: 9.99,
    priceLabel: "$9.99",
    badge: "gift-ready",
    hook: "A small woven basket set that works better as presentation than as a centerpiece gift alone.",
    why: "Best when you need packaging, a basket base, or a supporting Easter add-on at a very low spend.",
    bestFor: "Easter gift setup / add-on",
    vibe: "woven gifting extra",
    relationships: ["anyone"],
    intents: ["thoughtful", "cozy"],
    tabs: ["under-100", "cozy-home"],
    amazonAsin: "B0D4VB6R4H",
    sourceProductUrl: "https://www.amazon.com/dp/B0D4VB6R4H",
    query:
      "Easter Gift Basket Empty with Gift Bags and Ribbons, Easter Bunny Basket, Baby Gift Basket, Small Woven Rope Baskets for Organizing, Basket for Gifting, Storage Basket Bins",
    baseScore: 67,
  }),
  createImportedItem({
    id: "oneida-bunny-hop-plates",
    slug: "oneida-bunny-hop-dinner-plates",
    code: "GS-37",
    brand: "Oneida",
    name: "Oneida Bunny Hop Dinner Plates",
    priceValue: 15.98,
    priceLabel: "$15.98 - $19.95",
    badge: "serveware",
    hook: "A recognizable seasonal plate set that feels more polished than disposable holiday decor.",
    why: "Useful for spring hosting or Easter brunch when you want a seasonal pick that still feels functional.",
    bestFor: "wife / host gift / Easter brunch",
    vibe: "seasonal table set",
    relationships: ["wife", "anniversary", "anyone"],
    intents: ["cozy", "thoughtful"],
    tabs: ["cozy-home", "under-100"],
    amazonAsin: "B0DYG84MC3",
    sourceProductUrl: "https://www.amazon.com/dp/B0DYG84MC3",
    query: "Oneida 898192 Bunny Hop Dinner Plates, Set Of 4",
    baseScore: 72,
  }),
  createImportedItem({
    id: "satin-halter-maxi-dress",
    slug: "satin-halter-backless-maxi-dress",
    code: "GS-38",
    name: "Satin Halter Backless Maxi Dress",
    priceValue: 49.99,
    priceLabel: "$49.99",
    badge: "wedding guest",
    hook: "A satin halter dress with obvious event and vacation energy.",
    why: "Stronger when you want a dressier apparel gift that reads current and occasion-specific instead of basic.",
    bestFor: "girlfriend / wife / wedding guest season",
    vibe: "sleek event dress",
    intents: ["looks-expensive", "viral", "thoughtful"],
    tabs: ["looks-expensive", "best-overall", "under-100"],
    amazonAsin: "B0CQFRYHMR",
    sourceProductUrl: "https://www.amazon.com/dp/B0CQFRYHMR",
    query:
      "Summer Satin Halter Backless Maxi Dresses for Women 2025 Silk Sleeveless Formal Wedding Guest Long Dress",
    baseScore: 79,
  }),
  createImportedItem({
    id: "soly-hux-ruffle-maxi-dress",
    slug: "soly-hux-ruffle-layered-halter-maxi-dress",
    code: "GS-39",
    brand: "SOLY HUX",
    name: "SOLY HUX Ruffle Layered Halter Maxi Dress",
    priceValue: 71.99,
    priceLabel: "$71.99 - $73.99",
    badge: "dressy",
    hook: "A more dramatic halter maxi with movement and clearer occasion value.",
    why: "Useful when she likes more feminine eventwear and you want the gift to feel visibly styled.",
    bestFor: "girlfriend / wife / summer events",
    vibe: "ruffled occasion dress",
    intents: ["looks-expensive", "thoughtful"],
    tabs: ["looks-expensive", "best-overall", "under-100"],
    amazonAsin: "B0FJFFMGDK",
    sourceProductUrl: "https://www.amazon.com/dp/B0FJFFMGDK",
    query:
      "SOLY HUX Women's Sundresses Ruffle Layered Halter Flowy Maxi Dress Elegant Wedding Guest Dresses",
    baseScore: 78,
  }),
  createImportedItem({
    id: "kirundo-pleated-maxi-dress",
    slug: "kirundo-pleated-a-line-maxi-dress",
    code: "GS-40",
    brand: "KIRUNDO",
    name: "KIRUNDO Pleated A-Line Maxi Dress",
    priceValue: 44.99,
    priceLabel: "$44.99 - $49.99",
    badge: "spring dress",
    hook: "A lower-risk maxi dress with pockets and a more classic A-line shape.",
    why: "Cleaner when you want occasionwear that feels wearable beyond one event and less revealing than trendier options.",
    bestFor: "wife / girlfriend / spring events",
    vibe: "easy formal flow",
    intents: ["thoughtful", "looks-expensive"],
    tabs: ["best-overall", "looks-expensive", "under-100"],
    amazonAsin: "B0D5QWV49N",
    sourceProductUrl: "https://www.amazon.com/dp/B0D5QWV49N",
    query:
      "KIRUNDO Wedding Guest Dresses for Women 2026 Spring Summer Short Sleeve Pleated Long Flowy A Line Formal Maxi Dress Pockets",
    baseScore: 80,
  }),
  createImportedItem({
    id: "prettygarden-one-shoulder-maxi",
    slug: "prettygarden-one-shoulder-maxi-dress",
    code: "GS-41",
    brand: "PRETTYGARDEN",
    name: "PRETTYGARDEN One-Shoulder Ruched Maxi Dress",
    priceValue: 39.99,
    priceLabel: "$39.99",
    badge: "cocktail",
    hook: "A one-shoulder bodycon option with more date-night and party energy.",
    why: "Best when she likes trendier occasionwear and you want a gift that feels overtly dressed up.",
    bestFor: "girlfriend / wife / party season",
    vibe: "sleek night-out dress",
    intents: ["looks-expensive", "viral"],
    tabs: ["looks-expensive", "under-100"],
    amazonAsin: "B0BYHLBFVD",
    sourceProductUrl: "https://www.amazon.com/dp/B0BYHLBFVD",
    query:
      "PRETTYGARDEN Women's 2026 Wedding Guest Cocktail Dresses One Off The Shoulder Ruched Bodycon Formal Maxi Party Summer Outfits",
    baseScore: 77,
  }),
  createImportedItem({
    id: "miyuki-rustic-vase",
    slug: "miyuki-rustic-terracotta-vase",
    code: "GS-42",
    brand: "MIYUKI",
    name: "MIYUKI Rustic Terracotta Vase",
    priceValue: 34.99,
    priceLabel: "$34.99",
    badge: "ceramic",
    hook: "A rustic pottery vase that adds texture without needing much styling help.",
    why: "Strong when she likes home decor with earthy materials and a calmer neutral look.",
    bestFor: "wife / home decor / shelf styling",
    vibe: "rustic tabletop ceramic",
    relationships: ["wife", "anniversary", "anyone"],
    intents: ["cozy", "looks-expensive", "thoughtful"],
    tabs: ["cozy-home", "looks-expensive", "under-100"],
    amazonAsin: "B0FPCBWSMR",
    sourceProductUrl: "https://www.amazon.com/dp/B0FPCBWSMR",
    query:
      "MIYUKI Rustic Vase for Home Decor, Decorative Pottery Terracotta Vase for Living Room, Table, Shelf, Handcraft Vintage Ceramic Vase 6.7in H x 8.2in W",
    baseScore: 76,
  }),
  createImportedItem({
    id: "ceramic-floor-vase",
    slug: "large-ceramic-floor-vase",
    code: "GS-43",
    name: "Large Ceramic Floor Vase",
    priceValue: 59.99,
    priceLabel: "$59.99 - $86.99",
    badge: "floor decor",
    hook: "A larger decor piece that changes a room faster than a small accent item.",
    why: "Better when you want the home gift to read more substantial and visually obvious.",
    bestFor: "wife / living room / home refresh",
    vibe: "statement floor ceramic",
    relationships: ["wife", "anniversary", "anyone"],
    intents: ["cozy", "looks-expensive", "thoughtful"],
    tabs: ["cozy-home", "looks-expensive", "under-100"],
    query: "Ceramic Vase - Large Tall Floor Vase for Centerpieces",
    baseScore: 74,
  }),
  createImportedItem({
    id: "rustic-vase-set",
    slug: "rustic-vase-set-of-3",
    code: "GS-44",
    name: "Rustic Vase Set of 3",
    priceValue: 29.99,
    priceLabel: "$29.99 - $31.99",
    badge: "vase set",
    hook: "An easy neutral decor set that works well if she already styles shelves or tables.",
    why: "A lower-risk home pick because multiple pieces make it feel fuller without a big budget.",
    bestFor: "wife / apartment / shelf styling",
    vibe: "neutral decor trio",
    relationships: ["wife", "anniversary", "anyone"],
    intents: ["cozy", "thoughtful", "looks-expensive"],
    tabs: ["cozy-home", "under-100", "looks-expensive"],
    amazonAsin: "B0BYSFGVLC",
    sourceProductUrl: "https://www.amazon.com/dp/B0BYSFGVLC",
    query:
      "Ceramic Vase Set of 3, Rustic Vases Home Decor Neutral Farmhouse Decor Vase for Bouquet Pampas Grass Dried Fresh Flowers, Living Room, Kitchen, Bedroom, Bathroom",
    baseScore: 75,
  }),
  createImportedItem({
    id: "ninehaoou-scroll-vase",
    slug: "ninehaoou-scroll-vase",
    code: "GS-45",
    brand: "Ninehaoou",
    name: "Ninehaoou Ceramic Scroll Vase",
    priceValue: 23.99,
    priceLabel: "$23.99 - $46.99",
    badge: "terracotta",
    hook: "A smaller antique-style vase that adds texture to desks, shelves, or countertops.",
    why: "Useful when you want a decor gift with visible character at a lower spend.",
    bestFor: "wife / shelf decor / small-space styling",
    vibe: "antique ceramic detail",
    relationships: ["wife", "anniversary", "anyone"],
    intents: ["cozy", "thoughtful"],
    tabs: ["cozy-home", "under-100"],
    query:
      "Ninehaoou Ceramic Scroll Vase 5.1 Inch Rustic Plant Pots Flower Pot for Indoor Plants Home Kitchen Decor Farmhouse Antique Decorative Gifts",
    baseScore: 72,
  }),
  createImportedItem({
    id: "hugo-boss-bottled-beyond",
    slug: "hugo-boss-bottled-beyond",
    code: "GS-46",
    brand: "Hugo Boss",
    name: "Hugo Boss Bottled Beyond Eau de Parfum",
    priceValue: 155,
    priceLabel: "$155.00",
    badge: "fragrance",
    hook: "A premium woody fragrance with stronger gift presence than a small accessory.",
    why: "Works when the buy is more about brand recognition and presentation than novelty.",
    bestFor: "wife / premium gift / fragrance",
    vibe: "designer fragrance pick",
    relationships: ["wife", "anniversary", "anyone"],
    intents: ["looks-expensive", "thoughtful"],
    tabs: ["looks-expensive", "best-overall", "daily-use"],
    amazonAsin: "B0F1C2P82S",
    sourceProductUrl: "https://www.amazon.com/dp/B0F1C2P82S",
    query:
      "Hugo Boss Bottled Beyond Eau de Parfum Woody Men's Cologne With Notes of Ginger & Leather Long Lasting Fragrance",
    baseScore: 77,
  }),
  createImportedItem({
    id: "marc-jacobs-perfect-absolute",
    slug: "marc-jacobs-perfect-absolute",
    code: "GS-47",
    brand: "Marc Jacobs",
    name: "Marc Jacobs Perfect Absolute Eau de Parfum",
    priceValue: 99,
    priceLabel: "$99.00 - $165.00",
    badge: "designer",
    hook: "A recognizable designer fragrance that feels more elevated than a random beauty pick.",
    why: "A cleaner premium lane when she already likes fragrance and the goal is obvious brand polish.",
    bestFor: "girlfriend / wife / fragrance",
    vibe: "designer scent upgrade",
    intents: ["looks-expensive", "thoughtful"],
    tabs: ["looks-expensive", "best-overall"],
    amazonAsin: "B0FDCW4288",
    sourceProductUrl: "https://www.amazon.com/dp/B0FDCW4288",
    query:
      "Marc Jacobs Perfect Absolute Eau de Parfum Ambery Women's Perfume With Notes Caramelized Fig Accord, Jasmine Absolu & Rich Amber Accord",
    baseScore: 81,
  }),
  createImportedItem({
    id: "gucci-flora-gorgeous-magnolia",
    slug: "gucci-flora-gorgeous-magnolia",
    code: "GS-48",
    brand: "Gucci",
    name: "Gucci Flora Gorgeous Magnolia Eau de Parfum",
    priceValue: 45.89,
    priceLabel: "$45.89",
    badge: "designer",
    hook: "A very recognizable fragrance name that reads premium fast.",
    why: "Useful when you want a branded beauty gift with stronger luxury signaling than a generic scent.",
    bestFor: "girlfriend / wife / beauty",
    vibe: "luxury fragrance flex",
    intents: ["looks-expensive", "thoughtful", "viral"],
    tabs: ["looks-expensive", "best-overall", "under-100"],
    amazonAsin: "B0CG51HPWW",
    sourceProductUrl: "https://www.amazon.com/dp/B0CG51HPWW",
    query: "Gucci Flora Gorgeous Magnolia by Gucci for Women 1.0 oz Eau de Parfum Spray",
    baseScore: 82,
  }),
  createImportedItem({
    id: "artificial-olive-tree-1026",
    slug: "artificial-olive-tree-1026",
    code: "GS-49",
    name: "Artificial Olive Tree 1026",
    priceValue: 239.99,
    priceLabel: "$239.99",
    badge: "statement tree",
    hook: "A large faux olive tree that makes a room feel finished in one move.",
    why: "A better big decor gift when you want scale and a more noticeable home impact.",
    bestFor: "wife / home refresh / larger spaces",
    vibe: "tall greenery statement",
    relationships: ["wife", "anniversary", "anyone"],
    intents: ["cozy", "looks-expensive", "thoughtful"],
    tabs: ["cozy-home", "looks-expensive", "best-overall"],
    query: "Artificial Olive Tree1026 7+8",
    baseScore: 74,
  }),
  createImportedItem({
    id: "faux-olive-tree-planter",
    slug: "faux-olive-tree-planter",
    code: "GS-50",
    name: "Tall Faux Olive Tree with Planter",
    priceValue: 65.99,
    priceLabel: "$65.99 - $103.99",
    badge: "olive tree",
    hook: "A softer-price faux olive tree that still gives the same room-finish effect.",
    why: "Useful when you want the look of a statement plant without going to the highest spend tier.",
    bestFor: "wife / apartment / living room",
    vibe: "styled indoor greenery",
    relationships: ["wife", "anniversary", "anyone"],
    intents: ["cozy", "looks-expensive", "thoughtful"],
    tabs: ["cozy-home", "looks-expensive", "under-100"],
    amazonAsin: "B0DM1Y2FP4",
    sourceProductUrl: "https://www.amazon.com/dp/B0DM1Y2FP4",
    query:
      "Olive Trees Artificial Indoor, Tall Faux Olive Tree with Moss and Planter, Artificial Plants Indoor with Natural Wood Trunk and Lifelike Fruits, Fake Tree for Home Office Living Room Decor",
    baseScore: 76,
  }),
  createImportedItem({
    id: "black-olive-tree",
    slug: "artificial-black-olive-tree",
    code: "GS-51",
    name: "Artificial Black Olive Tree",
    priceValue: 49.99,
    priceLabel: "$49.99 - $69.99",
    badge: "olive tree",
    hook: "A more affordable faux tree that still adds height and texture to a room.",
    why: "A cleaner decor gift when you want something bigger than tabletop pieces without crossing into premium pricing.",
    bestFor: "wife / home decor / office",
    vibe: "budget statement greenery",
    relationships: ["wife", "anniversary", "anyone"],
    intents: ["cozy", "thoughtful"],
    tabs: ["cozy-home", "under-100"],
    amazonAsin: "B0DDC4YKTR",
    sourceProductUrl: "https://www.amazon.com/dp/B0DDC4YKTR",
    query:
      "Artificial Black Olive Trees, Fake Floor Silk Plants with Real Wood Trunk, Lifelike Foliage Ideal for Home & Office & Apartment Decor",
    baseScore: 73,
  }),
];
