export const seoSite = {
  name: "ShopForHer",
  url: "https://shopforher.org",
  updatedAt: "2026-03-06",
  description: "Fast gift picks for men buying for her.",
  affiliateTag: "giftsher-20",
  affiliateBaseUrl: "https://www.amazon.com/s",
};

export const seoCatalog = [
  {
    id: "silk-pillowcase",
    slug: "mulberry-silk-pillowcase-set",
    name: "Mulberry Silk Pillowcase Set",
    priceLabel: "$49 - $79",
    badge: "easy yes",
    hook: "Quiet luxury without trying too hard.",
    why: "Feels polished, feminine, and expensive without needing her exact size or taste.",
    bestFor: "girlfriend / wife / new relationship",
    query: "mulberry silk pillowcase set gift for her",
  },
  {
    id: "temperature-mug",
    slug: "temperature-control-mug",
    name: "Temperature-Control Mug",
    priceLabel: "$99 - $129",
    badge: "viral",
    hook: "Looks premium and gets used every day.",
    why: "A strong wife or girlfriend gift because it solves an annoying problem and feels upgraded immediately.",
    bestFor: "wife / girlfriend / coffee or tea",
    query: "temperature control mug gift for her",
  },
  {
    id: "digital-frame",
    slug: "digital-picture-frame",
    name: "Digital Picture Frame",
    priceLabel: "$129 - $179",
    badge: "wife-safe",
    hook: "Personal without feeling cheesy.",
    why: "One of the cleanest meaningful gifts for wives because it feels emotional the second photos are loaded.",
    bestFor: "wife / anniversary / home",
    query: "digital picture frame gift for wife",
  },
  {
    id: "mini-photo-printer",
    slug: "mini-photo-printer",
    name: "Mini Photo Printer",
    priceLabel: "$69 - $129",
    badge: "viral",
    hook: "Current, social, and very giftable.",
    why: "Easy girlfriend pick because it feels fun, personal, and shareable without being too serious.",
    bestFor: "girlfriend / anniversary / travel",
    query: "mini photo printer gift for girlfriend",
  },
  {
    id: "sunrise-alarm",
    slug: "sunrise-alarm-clock",
    name: "Sunrise Alarm Clock",
    priceLabel: "$59 - $109",
    badge: "smart pick",
    hook: "Calm, modern, and hard to hate.",
    why: "Feels wellness-forward and designed, which makes it a good choice when you want thoughtful without overdoing it.",
    bestFor: "girlfriend / wife / home routine",
    query: "sunrise alarm clock gift for her",
  },
  {
    id: "luxury-throw",
    slug: "luxury-throw-blanket",
    name: "Luxury Throw Blanket",
    priceLabel: "$39 - $89",
    badge: "comfort hit",
    hook: "Soft, elevated, no overthinking required.",
    why: "Very safe because it feels expensive, feminine, and cozy without forcing a specific personal taste.",
    bestFor: "girlfriend / wife / apartment",
    query: "luxury throw blanket gift for her",
  },
  {
    id: "walking-pad",
    slug: "compact-walking-pad",
    name: "Compact Walking Pad",
    priceLabel: "$179 - $329",
    badge: "big upgrade",
    hook: "A serious home-wellness move.",
    why: "The kind of wife gift that reads as useful, current, and more substantial than a small accessory.",
    bestFor: "wife / remote work / wellness",
    query: "compact walking pad gift for wife",
  },
  {
    id: "earbuds",
    slug: "noise-canceling-earbuds",
    name: "Noise-Canceling Earbuds",
    priceLabel: "$49 - $159",
    badge: "daily win",
    hook: "Useful enough to be a very safe bet.",
    why: "One of the easiest gifts for a girlfriend or wife because the use case is immediate and obvious.",
    bestFor: "girlfriend / wife / commute",
    query: "noise canceling earbuds gift for her",
  },
  {
    id: "projector",
    slug: "portable-projector",
    name: "Portable Projector",
    priceLabel: "$89 - $189",
    badge: "date-night",
    hook: "A more memorable gift than another small object.",
    why: "Great when you want the gift to feel like an experience and a home upgrade at the same time.",
    bestFor: "wife / girlfriend / date nights",
    query: "portable projector gift for couples",
  },
  {
    id: "magsafe-stand",
    slug: "magsafe-charging-stand",
    name: "MagSafe Charging Stand",
    priceLabel: "$29 - $79",
    badge: "clean desk",
    hook: "Minimal, useful, and visually tidy.",
    why: "A professional-feeling option when she likes neat spaces, bedside setups, or a more polished desk.",
    bestFor: "girlfriend / wife / desk setup",
    query: "magsafe charging stand gift for her",
  },
  {
    id: "jewelry-case",
    slug: "structured-jewelry-case",
    name: "Structured Jewelry Case",
    priceLabel: "$54 - $84",
    badge: "polished",
    hook: "Looks personal and expensive without being risky.",
    why: "A strong pick because it feels feminine, organized, and clearly chosen for her rather than bought at random.",
    bestFor: "girlfriend / wife / travel",
    query: "structured jewelry case gift for her",
  },
  {
    id: "candle-warmer",
    slug: "candle-warmer-lamp",
    name: "Candle Warmer Lamp",
    priceLabel: "$32 - $56",
    badge: "cozy",
    hook: "Very apartment-friendly and surprisingly elevated.",
    why: "Feels warm, aesthetic, and feminine, which makes it a low-risk cozy-home gift for a girlfriend or wife.",
    bestFor: "girlfriend / wife / apartment",
    query: "candle warmer lamp gift for her",
  },
  {
    id: "vanity-mirror",
    slug: "led-vanity-mirror",
    name: "LED Vanity Mirror",
    priceLabel: "$89 - $139",
    badge: "setup upgrade",
    hook: "A higher-end beauty-space upgrade that still feels practical.",
    why: "Useful, visual, and clearly premium, which makes it a stronger wife or long-term girlfriend option.",
    bestFor: "wife / girlfriend / beauty setup",
    query: "led vanity mirror gift for her",
  },
  {
    id: "cashmere-robe",
    slug: "cashmere-feel-robe",
    name: "Cashmere-Feel Robe",
    priceLabel: "$109 - $159",
    badge: "wife-level",
    hook: "Soft luxury that reads intentional fast.",
    why: "One of the better elevated home gifts because it feels personal, premium, and clearly for her comfort.",
    bestFor: "wife / anniversary / home",
    query: "luxury robe gift for wife",
  },
];

export const seoGuides = [
  {
    slug: "gifts-for-girlfriend",
    label: "Gifts for girlfriend",
    group: "relationship",
    groupLabel: "Relationship",
    title: "Best gifts for girlfriends in 2026 | ShopForHer",
    h1: "Best gifts for girlfriends in 2026",
    description: "Low-risk, popular gifts for men buying for a girlfriend right now.",
    intro: "Start with clean picks that feel current, easy to receive, and fast to buy.",
    itemIds: ["silk-pillowcase", "mini-photo-printer", "jewelry-case", "earbuds", "candle-warmer", "sunrise-alarm"],
    related: ["best-gifts-under-100", "viral-gifts-for-her", "new-relationship-gifts-for-her"],
  },
  {
    slug: "gifts-for-wife",
    label: "Gifts for wife",
    group: "relationship",
    groupLabel: "Relationship",
    title: "Best gifts for wives in 2026 | ShopForHer",
    h1: "Best gifts for wives in 2026",
    description: "Higher-confidence gift picks for wives, with stronger quality and daily-use upside.",
    intro: "These are the better answers when you want something polished, useful, and easy to stand behind.",
    itemIds: ["digital-frame", "temperature-mug", "cashmere-robe", "vanity-mirror", "walking-pad", "projector"],
    related: ["anniversary-gifts-for-her", "luxury-gifts-for-her", "daily-use-gifts-for-her"],
  },
  {
    slug: "anniversary-gifts-for-her",
    label: "Anniversary gifts",
    group: "moments",
    groupLabel: "Moment",
    title: "Best anniversary gifts for her in 2026 | ShopForHer",
    h1: "Best anniversary gifts for her in 2026",
    description: "Sharper anniversary gifts that feel intentional without getting cheesy.",
    intro: "The cleanest anniversary picks usually feel personal, premium, or experience-driven.",
    itemIds: ["digital-frame", "projector", "cashmere-robe", "silk-pillowcase", "jewelry-case", "mini-photo-printer"],
    related: ["gifts-for-wife", "date-night-gifts-for-her", "luxury-gifts-for-her"],
  },
  {
    slug: "birthday-gifts-for-girlfriend",
    label: "Birthday for girlfriend",
    group: "moments",
    groupLabel: "Moment",
    title: "Best birthday gifts for girlfriends in 2026 | ShopForHer",
    h1: "Best birthday gifts for girlfriends in 2026",
    description: "Birthday gifts for girlfriends that feel current, giftable, and easy to buy fast.",
    intro: "Use this lane when you want a present that feels like a yes immediately, not something she has to work around.",
    itemIds: ["mini-photo-printer", "jewelry-case", "silk-pillowcase", "earbuds", "candle-warmer", "magsafe-stand"],
    related: ["gifts-for-girlfriend", "viral-gifts-for-her", "best-gifts-under-100"],
  },
  {
    slug: "birthday-gifts-for-wife",
    label: "Birthday for wife",
    group: "moments",
    groupLabel: "Moment",
    title: "Best birthday gifts for wives in 2026 | ShopForHer",
    h1: "Best birthday gifts for wives in 2026",
    description: "Birthday gifts for wives that feel more substantial, polished, and worth opening.",
    intro: "This page stays on stronger upgrades and safer premium picks.",
    itemIds: ["temperature-mug", "digital-frame", "vanity-mirror", "cashmere-robe", "projector", "walking-pad"],
    related: ["gifts-for-wife", "anniversary-gifts-for-her", "luxury-gifts-for-her"],
  },
  {
    slug: "best-gifts-under-75",
    label: "Best gifts under $75",
    group: "budget",
    groupLabel: "Budget",
    title: "Best gifts for her under $75 in 2026 | ShopForHer",
    h1: "Best gifts for her under $75 in 2026",
    description: "Budget gift picks that still look clean and intentional.",
    intro: "This is the low-risk lane when you want to spend less without making the gift feel cheap.",
    itemIds: ["candle-warmer", "magsafe-stand", "luxury-throw", "jewelry-case", "silk-pillowcase"],
    related: ["best-gifts-under-100", "gifts-for-girlfriend", "last-minute-gifts-for-her"],
  },
  {
    slug: "best-gifts-under-100",
    label: "Best gifts under $100",
    group: "budget",
    groupLabel: "Budget",
    title: "Best gifts for her under $100 in 2026 | ShopForHer",
    h1: "Best gifts for her under $100 in 2026",
    description: "Strong gift picks for her under $100, built around easy wins and clean buys.",
    intro: "For most men, this is the best spending range. Enough room to look strong without turning the gift into a production.",
    itemIds: ["silk-pillowcase", "mini-photo-printer", "luxury-throw", "earbuds", "jewelry-case", "candle-warmer", "sunrise-alarm"],
    related: ["gifts-for-girlfriend", "best-gifts-under-75", "amazon-gifts-for-her"],
  },
  {
    slug: "viral-gifts-for-her",
    label: "Viral gifts",
    group: "angle",
    groupLabel: "Angle",
    title: "Viral gifts for her in 2026 | ShopForHer",
    h1: "Viral gifts for her in 2026",
    description: "Current, shareable, high-click gift ideas for her.",
    intro: "Use this page when you want something that already feels current online and easy to justify in real life.",
    itemIds: ["temperature-mug", "mini-photo-printer", "earbuds", "vanity-mirror", "projector", "walking-pad"],
    related: ["gifts-for-girlfriend", "tech-gifts-for-her", "amazon-gifts-for-her"],
  },
  {
    slug: "luxury-gifts-for-her",
    label: "Luxury gifts",
    group: "angle",
    groupLabel: "Angle",
    title: "Luxury gifts for her in 2026 | ShopForHer",
    h1: "Luxury gifts for her in 2026",
    description: "Cleaner premium gifts for her that read expensive fast.",
    intro: "These picks lean more polished and elevated without turning flashy or random.",
    itemIds: ["cashmere-robe", "digital-frame", "temperature-mug", "vanity-mirror", "walking-pad", "silk-pillowcase"],
    related: ["gifts-for-wife", "anniversary-gifts-for-her", "looks-expensive-gifts-for-her"],
  },
  {
    slug: "practical-gifts-for-her",
    label: "Practical gifts",
    group: "angle",
    groupLabel: "Angle",
    title: "Practical gifts for her in 2026 | ShopForHer",
    h1: "Practical gifts for her in 2026",
    description: "Useful gifts for her that still feel like a gift, not an errand.",
    intro: "The right practical gift solves a real problem and still feels selected for her, not just purchased fast.",
    itemIds: ["temperature-mug", "earbuds", "sunrise-alarm", "magsafe-stand", "walking-pad", "vanity-mirror"],
    related: ["daily-use-gifts-for-her", "best-gifts-under-100", "gifts-for-wife"],
  },
  {
    slug: "cozy-home-gifts-for-her",
    label: "Cozy home gifts",
    group: "angle",
    groupLabel: "Angle",
    title: "Cozy home gifts for her in 2026 | ShopForHer",
    h1: "Cozy home gifts for her in 2026",
    description: "Soft, apartment-friendly gifts for her that feel warm and easy to keep.",
    intro: "This lane works when you want comfort, home use, and a gift that lands without much explanation.",
    itemIds: ["luxury-throw", "candle-warmer", "cashmere-robe", "projector", "sunrise-alarm", "digital-frame"],
    related: ["gifts-for-homebodies", "date-night-gifts-for-her", "best-gifts-under-100"],
  },
  {
    slug: "tech-gifts-for-her",
    label: "Tech gifts",
    group: "angle",
    groupLabel: "Angle",
    title: "Tech gifts for her in 2026 | ShopForHer",
    h1: "Tech gifts for her in 2026",
    description: "Cleaner tech gifts for her that feel current, useful, and safe to buy.",
    intro: "The best tech picks here are simple to understand and easy to use the same day.",
    itemIds: ["temperature-mug", "digital-frame", "mini-photo-printer", "earbuds", "projector", "magsafe-stand"],
    related: ["viral-gifts-for-her", "practical-gifts-for-her", "daily-use-gifts-for-her"],
  },
  {
    slug: "new-relationship-gifts-for-her",
    label: "New relationship gifts",
    group: "relationship",
    groupLabel: "Relationship",
    title: "Best new relationship gifts for her in 2026 | ShopForHer",
    h1: "Best new relationship gifts for her in 2026",
    description: "Low-pressure gifts for new relationships that still feel sharp.",
    intro: "The move here is simple: thoughtful, attractive, and easy to say yes to.",
    itemIds: ["silk-pillowcase", "mini-photo-printer", "sunrise-alarm", "luxury-throw", "magsafe-stand", "candle-warmer"],
    related: ["gifts-for-girlfriend", "best-gifts-under-75", "last-minute-gifts-for-her"],
  },
  {
    slug: "gifts-for-her-who-has-everything",
    label: "For her who has everything",
    group: "relationship",
    groupLabel: "Relationship",
    title: "Best gifts for her who has everything in 2026 | ShopForHer",
    h1: "Best gifts for her who has everything in 2026",
    description: "Gift picks that feel less obvious and more chosen.",
    intro: "When she already buys what she wants, the better move is something useful, polished, or experience-adjacent.",
    itemIds: ["digital-frame", "mini-photo-printer", "projector", "jewelry-case", "vanity-mirror", "temperature-mug"],
    related: ["luxury-gifts-for-her", "anniversary-gifts-for-her", "tech-gifts-for-her"],
  },
  {
    slug: "last-minute-gifts-for-her",
    label: "Last-minute gifts",
    group: "moments",
    groupLabel: "Moment",
    title: "Best last-minute gifts for her in 2026 | ShopForHer",
    h1: "Best last-minute gifts for her in 2026",
    description: "Fast, low-friction gifts for her when you need a strong answer quickly.",
    intro: "These are the picks that make sense when the main requirement is speed without looking careless.",
    itemIds: ["magsafe-stand", "candle-warmer", "silk-pillowcase", "earbuds", "jewelry-case", "luxury-throw"],
    related: ["amazon-gifts-for-her", "best-gifts-under-75", "gifts-for-girlfriend"],
  },
  {
    slug: "date-night-gifts-for-her",
    label: "Date-night gifts",
    group: "moments",
    groupLabel: "Moment",
    title: "Best date-night gifts for her in 2026 | ShopForHer",
    h1: "Best date-night gifts for her in 2026",
    description: "Gift ideas that pair well with a date and feel more memorable than a basic object.",
    intro: "This page leans toward gifts that create a shared night, a softer mood, or a stronger reveal.",
    itemIds: ["projector", "mini-photo-printer", "cashmere-robe", "candle-warmer", "digital-frame", "luxury-throw"],
    related: ["anniversary-gifts-for-her", "cozy-home-gifts-for-her", "gifts-for-wife"],
  },
  {
    slug: "amazon-gifts-for-her",
    label: "Amazon gifts",
    group: "budget",
    groupLabel: "Budget",
    title: "Best Amazon gifts for her in 2026 | ShopForHer",
    h1: "Best Amazon gifts for her in 2026",
    description: "Fast Amazon gift picks for her, chosen for clean fit and faster checkout.",
    intro: "If the goal is speed, this is the shortest path from product page to checkout.",
    itemIds: ["silk-pillowcase", "temperature-mug", "mini-photo-printer", "earbuds", "jewelry-case", "candle-warmer"],
    related: ["last-minute-gifts-for-her", "best-gifts-under-100", "viral-gifts-for-her"],
  },
  {
    slug: "gifts-for-homebodies",
    label: "Gifts for homebodies",
    group: "angle",
    groupLabel: "Angle",
    title: "Best gifts for homebodies in 2026 | ShopForHer",
    h1: "Best gifts for homebodies in 2026",
    description: "At-home gifts that feel soft, useful, and easy to keep around.",
    intro: "These picks work when she likes her apartment, routines, and comfort more than big gestures.",
    itemIds: ["luxury-throw", "candle-warmer", "cashmere-robe", "sunrise-alarm", "digital-frame", "projector"],
    related: ["cozy-home-gifts-for-her", "date-night-gifts-for-her", "gifts-for-wife"],
  },
  {
    slug: "daily-use-gifts-for-her",
    label: "Daily-use gifts",
    group: "angle",
    groupLabel: "Angle",
    title: "Best daily-use gifts for her in 2026 | ShopForHer",
    h1: "Best daily-use gifts for her in 2026",
    description: "Gifts for her that earn their place because they get used all the time.",
    intro: "The cleanest daily-use gifts solve a small problem, look good, and start paying off right away.",
    itemIds: ["temperature-mug", "earbuds", "magsafe-stand", "sunrise-alarm", "vanity-mirror", "walking-pad"],
    related: ["practical-gifts-for-her", "tech-gifts-for-her", "gifts-for-wife"],
  },
  {
    slug: "looks-expensive-gifts-for-her",
    label: "Looks expensive",
    group: "angle",
    groupLabel: "Angle",
    title: "Gifts for her that look expensive in 2026 | ShopForHer",
    h1: "Gifts for her that look expensive in 2026",
    description: "Gifts for her that feel polished and premium without forcing a huge spend.",
    intro: "This lane is about visual payoff, clean presentation, and picks that read stronger than their price.",
    itemIds: ["silk-pillowcase", "jewelry-case", "cashmere-robe", "vanity-mirror", "digital-frame", "luxury-throw"],
    related: ["luxury-gifts-for-her", "best-gifts-under-100", "gifts-for-girlfriend"],
  },
];

export const featuredSeoGuides = [
  "gifts-for-girlfriend",
  "gifts-for-wife",
  "best-gifts-under-100",
  "viral-gifts-for-her",
  "looks-expensive-gifts-for-her",
  "date-night-gifts-for-her",
].map((slug) => seoGuides.find((guide) => guide.slug === slug)).filter(Boolean);

export const featuredSeoProducts = [
  "silk-pillowcase",
  "temperature-mug",
  "digital-frame",
  "mini-photo-printer",
  "earbuds",
  "jewelry-case",
].map((id) => seoCatalog.find((gift) => gift.id === id)).filter(Boolean);

export const seoDateCities = [
  {
    slug: "los-angeles",
    city: "Los Angeles",
    title: "Best date spots in Los Angeles | ShopForHer",
    h1: "Best date spots in Los Angeles",
    description: "Simple Los Angeles date spots with easy booking paths and low-friction date ideas.",
    intro: "Use this page when you need a clean date plan in Los Angeles without overworking it.",
    spots: [
      { name: "Low-light dinner room", type: "Dinner", area: "West Hollywood", note: "Strong first answer when you want the night handled.", bookingUrl: "https://www.opentable.com/" },
      { name: "Natural wine bar", type: "Drinks", area: "Silver Lake", note: "Better for a lower-pressure date that still feels intentional.", bookingUrl: "https://www.opentable.com/" },
      { name: "Rooftop dinner spot", type: "Night out", area: "Downtown LA", note: "Use this when you want a cleaner visual payoff.", bookingUrl: "https://www.opentable.com/" },
      { name: "Dessert and cocktail bar", type: "After dinner", area: "Beverly Grove", note: "Shorter plan. Easier to say yes to.", bookingUrl: "https://www.opentable.com/" },
    ],
  },
  {
    slug: "new-york",
    city: "New York",
    title: "Best date spots in New York | ShopForHer",
    h1: "Best date spots in New York",
    description: "Simple New York date spots with easy reservation links and cleaner date planning.",
    intro: "This is the low-friction New York date list for dinner, drinks, or a cleaner second move.",
    spots: [
      { name: "Quiet neighborhood dinner room", type: "Dinner", area: "West Village", note: "Reliable room, good lighting, easy conversation.", bookingUrl: "https://www.opentable.com/" },
      { name: "Natural wine bar", type: "Drinks", area: "Lower East Side", note: "Good when dinner feels too heavy.", bookingUrl: "https://www.opentable.com/" },
      { name: "Dessert room", type: "Dessert", area: "SoHo", note: "Short plan, clean close.", bookingUrl: "https://www.opentable.com/" },
      { name: "Weekend brunch room", type: "Day date", area: "Brooklyn", note: "Useful when night plans are too much.", bookingUrl: "https://www.opentable.com/" },
    ],
  },
  {
    slug: "chicago",
    city: "Chicago",
    title: "Best date spots in Chicago | ShopForHer",
    h1: "Best date spots in Chicago",
    description: "Straightforward Chicago date spots with cleaner booking paths and easy date ideas.",
    intro: "Keep it simple: one good reservation, one clean area, one easy plan.",
    spots: [
      { name: "Low-light dinner room", type: "Dinner", area: "West Loop", note: "Strong if you want the date to feel handled immediately.", bookingUrl: "https://www.opentable.com/" },
      { name: "Cocktail bar", type: "Drinks", area: "River North", note: "Good for a short plan that still looks considered.", bookingUrl: "https://www.opentable.com/" },
      { name: "Dessert spot", type: "After dinner", area: "Lincoln Park", note: "Easy second stop without dragging the night out.", bookingUrl: "https://www.opentable.com/" },
      { name: "Brunch room", type: "Day date", area: "Wicker Park", note: "Cleaner day-date move.", bookingUrl: "https://www.opentable.com/" },
    ],
  },
  {
    slug: "miami",
    city: "Miami",
    title: "Best date spots in Miami | ShopForHer",
    h1: "Best date spots in Miami",
    description: "Simple Miami date spots with easy booking paths for dinner, drinks, and low-pressure plans.",
    intro: "Use this page when you want the fastest path to a date plan in Miami.",
    spots: [
      { name: "Rooftop dinner room", type: "Dinner", area: "Brickell", note: "For a stronger first impression without overcomplicating it.", bookingUrl: "https://www.opentable.com/" },
      { name: "Wine bar", type: "Drinks", area: "Wynwood", note: "Lower pressure, easier start.", bookingUrl: "https://www.opentable.com/" },
      { name: "Dessert and cocktail spot", type: "After dinner", area: "Design District", note: "Good short format.", bookingUrl: "https://www.opentable.com/" },
      { name: "Brunch room", type: "Day date", area: "Coconut Grove", note: "Simple daytime backup.", bookingUrl: "https://www.opentable.com/" },
    ],
  },
];

export const seoHotStories = [
  {
    slug: "viral-gifts-for-girlfriend",
    label: "For girlfriend",
    title: "Viral gifts for girlfriends in 2026 | ShopForHer",
    h1: "Viral gifts for girlfriends in 2026",
    description: "Current gifts for girlfriends that feel popular online and easy to buy fast.",
    intro: "This is the cleaner viral lane for girlfriend gifts: current, low-pressure, and easy to open.",
    views: "124K views",
    duration: "0:31",
    trendLabel: "Rising now",
    itemIds: ["mini-photo-printer", "silk-pillowcase", "jewelry-case", "earbuds", "candle-warmer"],
    relatedGuides: ["gifts-for-girlfriend", "viral-gifts-for-her", "best-gifts-under-100"],
  },
  {
    slug: "viral-gifts-for-wife",
    label: "For wife",
    title: "Viral gifts for wives in 2026 | ShopForHer",
    h1: "Viral gifts for wives in 2026",
    description: "Current wife gift picks with stronger quality and cleaner buying confidence.",
    intro: "These are the viral-looking picks that still hold up when you actually buy them for your wife.",
    views: "98K views",
    duration: "0:37",
    trendLabel: "Most opened",
    itemIds: ["temperature-mug", "digital-frame", "cashmere-robe", "vanity-mirror", "walking-pad"],
    relatedGuides: ["gifts-for-wife", "luxury-gifts-for-her", "daily-use-gifts-for-her"],
  },
  {
    slug: "viral-gifts-under-100",
    label: "Under $100",
    title: "Viral gifts for her under $100 in 2026 | ShopForHer",
    h1: "Viral gifts for her under $100 in 2026",
    description: "High-click gifts for her under $100 that still feel like a strong buy.",
    intro: "This is the fast-spend lane: current gifts, cleaner price point, less overthinking.",
    views: "141K views",
    duration: "0:29",
    trendLabel: "Budget lane",
    itemIds: ["silk-pillowcase", "mini-photo-printer", "earbuds", "jewelry-case", "candle-warmer", "luxury-throw"],
    relatedGuides: ["best-gifts-under-100", "best-gifts-under-75", "amazon-gifts-for-her"],
  },
  {
    slug: "looks-expensive-gifts-going-viral",
    label: "Looks expensive",
    title: "Gifts for her that look expensive and are going viral | ShopForHer",
    h1: "Gifts for her that look expensive and are going viral",
    description: "Polished gifts for her with stronger visual payoff and current attention.",
    intro: "This page is about visual strength: gifts that look sharper than the spend and already feel current.",
    views: "87K views",
    duration: "0:34",
    trendLabel: "Looks strong",
    itemIds: ["cashmere-robe", "digital-frame", "silk-pillowcase", "vanity-mirror", "jewelry-case"],
    relatedGuides: ["looks-expensive-gifts-for-her", "luxury-gifts-for-her", "anniversary-gifts-for-her"],
  },
  {
    slug: "useful-gifts-women-actually-use",
    label: "Actually useful",
    title: "Useful gifts women actually use in 2026 | ShopForHer",
    h1: "Useful gifts women actually use in 2026",
    description: "Practical gifts for her that still feel good when opened and better after week one.",
    intro: "These are the gifts that stop looking good only in the cart and start paying off in daily life.",
    views: "76K views",
    duration: "0:28",
    trendLabel: "Repeat use",
    itemIds: ["temperature-mug", "earbuds", "magsafe-stand", "sunrise-alarm", "walking-pad"],
    relatedGuides: ["practical-gifts-for-her", "daily-use-gifts-for-her", "tech-gifts-for-her"],
  },
  {
    slug: "cozy-gifts-trending-now",
    label: "Cozy home",
    title: "Cozy gifts trending now in 2026 | ShopForHer",
    h1: "Cozy gifts trending now in 2026",
    description: "Soft, apartment-friendly gifts for her that are trending now and easy to keep.",
    intro: "This lane works when you want the gift to feel warm, calm, and easy to live with.",
    views: "64K views",
    duration: "0:26",
    trendLabel: "Soft lane",
    itemIds: ["luxury-throw", "candle-warmer", "cashmere-robe", "projector", "sunrise-alarm"],
    relatedGuides: ["cozy-home-gifts-for-her", "gifts-for-homebodies", "date-night-gifts-for-her"],
  },
  {
    slug: "anniversary-gifts-trending-now",
    label: "Anniversary",
    title: "Anniversary gifts trending now in 2026 | ShopForHer",
    h1: "Anniversary gifts trending now in 2026",
    description: "Trending anniversary gifts for her that feel more intentional without turning cheesy.",
    intro: "These are the cleaner anniversary gifts getting attention right now.",
    views: "52K views",
    duration: "0:33",
    trendLabel: "Higher signal",
    itemIds: ["digital-frame", "projector", "cashmere-robe", "silk-pillowcase", "mini-photo-printer"],
    relatedGuides: ["anniversary-gifts-for-her", "luxury-gifts-for-her", "date-night-gifts-for-her"],
  },
  {
    slug: "new-relationship-gifts-trending-now",
    label: "New relationship",
    title: "New relationship gifts trending now in 2026 | ShopForHer",
    h1: "New relationship gifts trending now in 2026",
    description: "Trending gifts for a new relationship that feel sharp, simple, and low-pressure.",
    intro: "Keep the move easy: thoughtful, current, and not too much.",
    views: "43K views",
    duration: "0:24",
    trendLabel: "Low pressure",
    itemIds: ["silk-pillowcase", "mini-photo-printer", "sunrise-alarm", "luxury-throw", "magsafe-stand"],
    relatedGuides: ["new-relationship-gifts-for-her", "gifts-for-girlfriend", "best-gifts-under-75"],
  },
];
